using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Omicron_Pi
{
    public partial class SplashScreen : Form
    {
        public SplashScreen()
        {
            InitializeComponent();
        }

        private void openExistingConfigButton_Click(object sender, EventArgs e) => openFileDialog1.ShowDialog();

        private void openFileDialog1_FileOk(object sender, CancelEventArgs e)
        {
            if (openFileDialog1.FileName.Contains("config_remoteadmin.txt"))
            {
                Globals.configFileArray = File.ReadAllLines(openFileDialog1.FileName);
                Globals.configFile = File.ReadAllText(openFileDialog1.FileName);
                Globals.configFilePath = openFileDialog1.FileName;
                DialogResult = DialogResult.OK;
                Hide();
                return;
            }
            MessageBox.Show("Please selecet an existing config_remoteadmin.txt");
        }

        private void button2_Click(object sender, EventArgs e)
        {
            if (openFileDialog1.FileName.Contains("config_remoteadmin.txt"))
            {
                Globals.configFileArray = File.ReadAllLines(@".\TemplateConfig\DO NOT EDIT THIS FILE.txt");
                Globals.configFile = File.ReadAllText(@".\TemplateConfig\DO NOT EDIT THIS FILE.txt");
                Globals.configFilePath = @".\TemplateConfig\DO NOT EDIT THIS FILE.txt";
                DialogResult = DialogResult.OK;
                Hide();
                return;
            }
            MessageBox.Show("Please selecet an existing config_remoteadmin.txt");
        }

        private void SplashScreen_FormClosed(object sender, FormClosedEventArgs e)
        {
            if (e.CloseReason == CloseReason.UserClosing)
            {
                Application.Exit();
            }
        }
    }
}
